"""Module knowledge archive/retrieve/wiki APIs.

This module is the public Spotlights memory layer: archive evidence-bearing
records, retrieve ranked local records, and render a generated wiki. It is
intentionally phase-free and dependency-light.
"""

from spotlights_engine.module_knowledge.concepts import (
    CONCEPTS_SCHEMA_VERSION,
    ConceptKind,
    ConceptLinks,
    ConceptPage,
    ConceptVerifyIssue,
    ConceptVerifyReport,
    ConceptsLayout,
    IngestReport,
    IngestRequest,
    InlineIngestRequest,
    InlineSource,
    LightSourceRef,
    LintReport,
    QueryResult,
    RecordSourceRef,
    RecordsBackedIngestRequest,
    Wiki,
)
from spotlights_engine.module_knowledge.records import (
    SCHEMA_VERSION,
    ArchiveResult,
    KnowledgeBase,
    KnowledgeLayout,
    KnowledgeRecord,
    KnowledgeSourceType,
    Provenance,
    RetrieveRequest,
    RetrievedItem,
    SourceRef,
    TrustTier,
    WikiRenderResult,
    WikiRenderer,
    WikiVerificationIssue,
    WikiVerificationReport,
    record_from_agent_proposal,
    record_from_candidate,
    record_from_deep_research_proposal,
    record_from_finding,
    record_from_module,
    records_from_candidate_proposals,
    records_from_candidates,
    records_from_findings,
    records_from_module_deep_research,
    records_from_module_run,
    records_from_project_tree,
    records_from_spotlights_result,
    read_records,
    retrieve_records,
    verify_wiki,
    write_records,
)

__all__ = [
    # concepts layer
    "CONCEPTS_SCHEMA_VERSION",
    "ConceptKind",
    "ConceptLinks",
    "ConceptPage",
    "ConceptVerifyIssue",
    "ConceptVerifyReport",
    "ConceptsLayout",
    "IngestReport",
    "IngestRequest",
    "InlineIngestRequest",
    "InlineSource",
    "LightSourceRef",
    "LintReport",
    "QueryResult",
    "RecordSourceRef",
    "RecordsBackedIngestRequest",
    "Wiki",
    # records layer
    "SCHEMA_VERSION",
    "ArchiveResult",
    "KnowledgeBase",
    "KnowledgeLayout",
    "KnowledgeRecord",
    "KnowledgeSourceType",
    "Provenance",
    "RetrieveRequest",
    "RetrievedItem",
    "SourceRef",
    "TrustTier",
    "WikiRenderResult",
    "WikiRenderer",
    "WikiVerificationIssue",
    "WikiVerificationReport",
    "record_from_agent_proposal",
    "record_from_candidate",
    "record_from_deep_research_proposal",
    "records_from_candidate_proposals",
    "records_from_candidates",
    "records_from_findings",
    "records_from_module_run",
    "records_from_spotlights_result",
    "record_from_finding",
    "record_from_module",
    "records_from_module_deep_research",
    "records_from_project_tree",
    "read_records",
    "retrieve_records",
    "verify_wiki",
    "write_records",
]
