"""CORAL adapter (multi-file): task.yaml only.

CORAL spawns coding agents that edit a per-agent git worktree of the target
repo; a `Grader(TaskGrader)` scores each commit. CORAL auto-discovers the
grader at `grader/grader.py` by convention, so this adapter emits only
`task.yaml` — you write `grader/grader.py` yourself. Supports single- or
multi-target scope.
"""

from __future__ import annotations

from spotlights_engine.prep_evolve.adapters.base import GeneratedFile
from spotlights_engine.prep_evolve.digest import render_digest
from spotlights_engine.prep_evolve.spec import EvolveSpec, Target
from spotlights_engine.prep_evolve.yaml_emit import dump_yaml

_DEFAULT_MODEL = "sonnet"


def _candidate_target(spec: EvolveSpec) -> Target:
    for t in spec.targets:
        if t.scope_kind == "candidate":
            return t
    # Defensive: spec construction always puts the candidate first.
    return spec.targets[0]


def _scope_files(spec: EvolveSpec) -> list[str]:
    files: list[str] = []
    for t in spec.targets:
        if t.file not in files:
            files.append(t.file)
    return files


class CoralAdapter:
    name = "coral"

    def __init__(self, model: str | None = None) -> None:
        self._model = model or _DEFAULT_MODEL

    def supports(self, spec: EvolveSpec) -> tuple[bool, str]:
        return (True, "")

    def render(self, spec: EvolveSpec) -> list[GeneratedFile]:
        digest = render_digest(spec)
        cand = _candidate_target(spec)
        scope_files = _scope_files(spec)

        task_yaml = self._build_task_yaml(spec, cand, scope_files, digest)

        return [
            GeneratedFile(path="task.yaml", text=task_yaml),
        ]

    def _build_task_yaml(
        self,
        spec: EvolveSpec,
        cand: Target,
        scope_files: list[str],
        digest: str,
    ) -> str:
        name = f"{spec.run.repo_name} · {spec.module.qualified_name} · {cand.symbol}"
        description = self._description(spec, digest)
        tips = self._tips(cand, scope_files)

        task = {
            "task": {
                "name": name,
                "description": description,
                "tips": tips,
            },
            "grader": {
                # CORAL auto-discovers grader/grader.py by convention and
                # instantiates its Grader(TaskGrader) subclass — no entrypoint
                # or package install needed. You must write grader/grader.py
                # (see README) before scores are meaningful.
                "timeout": 600,
                "direction": spec.objective.direction,
                "args": {
                    "target_files": scope_files,
                    "correctness_oracle": cand.oracles.correctness,
                    "performance_oracle": cand.oracles.performance or "",
                    "primary_metric": cand.oracles.performance or "",
                },
            },
            "workspace": {
                "repo_path": spec.run.repo_path,
                "results_dir": "./results",
                "setup": [],
            },
            "agents": {
                "count": 1,
                "runtime": "claude_code",
                "model": self._model,
            },
        }
        header = (
            "# Generated by spotlights-engine prep-evolve.\n"
            "# Run: coral start --config task.yaml\n"
            "# You must write grader/grader.py (a Grader(TaskGrader) subclass) before\n"
            "# scores are meaningful — CORAL auto-discovers it by convention.\n"
        )
        return header + dump_yaml(task)

    def _description(self, spec: EvolveSpec, digest: str) -> str:
        lines = [
            f"Optimize {spec.run.repo_name} for: {spec.objective.goal} "
            f"(direction: {spec.objective.direction}).",
            "",
            "In-scope files:",
        ]
        for t in spec.targets:
            if t.scope_kind == "candidate" and t.line_start is not None:
                lines.append(
                    f"- {t.file}:{t.line_start}–{t.line_end} (`{t.symbol}`, the selected candidate)"
                )
            else:
                role = f" — {t.role}" if t.role else ""
                lines.append(f"- {t.file} (whole file{role})")
        lines.append("")
        lines.append(digest)
        return "\n".join(lines)

    def _tips(self, cand: Target, scope_files: list[str]) -> str:
        parts = []
        if cand.evolve_rationale:
            parts.append(cand.evolve_rationale)
        if cand.estimated_impact_explanation:
            parts.append(cand.estimated_impact_explanation)
        parts.append(
            "Stay within these files: " + ", ".join(scope_files) + ". "
            "Edits outside them are rejected by the grader."
        )
        return "\n\n".join(parts)


__all__ = ["CoralAdapter"]
