"""Nous (agentic-strategy-evolution) adapter: campaign.yaml + vendored
methodology prompts + optional bundle.yaml.

Nous runs experiment arms whose `code_changes[]` intents the executor turns
into patches. `campaign.yaml` must respect `additionalProperties: false`, so we
emit only schema-allowed keys; URLs/evidence stay in the digest /
`target_system.description`.
"""

from __future__ import annotations

import re
from pathlib import Path

from spotlights_engine.prep_evolve.adapters.base import GeneratedFile
from spotlights_engine.prep_evolve.digest import render_digest
from spotlights_engine.prep_evolve.spec import EvolveSpec, Target
from spotlights_engine.prep_evolve.yaml_emit import dump_yaml

# Repo-root-relative source of the methodology prompts we vendor.
_METHODOLOGY_REL = Path(
    "other_repos/agentic-strategy-evolution/prompts/methodology"
)


def _find_methodology_dir() -> Path | None:
    """Walk up from this file to the project root and locate the prompts dir."""
    here = Path(__file__).resolve()
    for parent in here.parents:
        candidate = parent / _METHODOLOGY_REL
        if candidate.is_dir():
            return candidate
    return None


def _candidate_target(spec: EvolveSpec) -> Target:
    for t in spec.targets:
        if t.scope_kind == "candidate":
            return t
    return spec.targets[0]


def _slug(text: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()
    return s or "run"


class NousAdapter:
    name = "nous"

    def __init__(self, model: str | None = None, emit_bundle: bool = True) -> None:
        self._model = model
        self._emit_bundle = emit_bundle

    def supports(self, spec: EvolveSpec) -> tuple[bool, str]:
        return (True, "")

    def render(self, spec: EvolveSpec) -> list[GeneratedFile]:
        digest = render_digest(spec)
        cand = _candidate_target(spec)

        files = [
            GeneratedFile(
                path="campaign.yaml",
                text=self._build_campaign(spec, cand, digest),
                overwrite="always",
            )
        ]
        if self._emit_bundle:
            files.append(
                GeneratedFile(
                    path="bundle.yaml",
                    text=self._build_bundle(spec, cand),
                    overwrite="always",
                )
            )
        files.extend(self._vendor_methodology())
        return files

    # --- campaign.yaml ---

    def _build_campaign(self, spec: EvolveSpec, cand: Target, digest: str) -> str:
        research_question = self._research_question(spec, cand)
        run_id = _slug(
            f"{spec.run.repo_name}-{spec.module.qualified_name}-"
            f"{cand.candidate_id or 'cand'}"
        )

        target_system: dict = {
            "name": spec.run.repo_name,
            "description": self._target_description(spec, digest),
        }
        metrics = self._observable_metrics(spec, cand)
        if metrics:  # minItems: 1 — omit the key entirely when empty
            target_system["observable_metrics"] = metrics
        knobs = self._controllable_knobs(spec)
        if knobs:
            target_system["controllable_knobs"] = knobs
        target_system["repo_path"] = spec.run.repo_path

        campaign: dict = {
            "research_question": research_question,
            "run_id": run_id,
            "target_system": target_system,
        }

        theory = self._theory_references(spec)
        if theory:
            campaign["theory_references"] = theory

        ground_truth = self._ground_truth(spec, cand)
        if ground_truth:
            campaign["ground_truth"] = ground_truth

        campaign["prompts"] = {"methodology_layer": "prompts/methodology"}

        if self._model:
            campaign["models"] = {"design": self._model, "execute_analyze": self._model}

        header = (
            "# Generated by spotlights-engine prep-evolve.\n"
            "# Run: NOUS_CAMPAIGN_PARENT=$PWD/nous_runs nous run campaign.yaml"
            f"{' --bundle bundle.yaml' if self._emit_bundle else ''}\n"
        )
        return header + dump_yaml(campaign)

    def _research_question(self, spec: EvolveSpec, cand: Target) -> str:
        sym = cand.symbol or cand.file
        return (
            f"Does changing `{sym}` in {spec.run.repo_name} achieve: "
            f"{spec.objective.goal}?"
        )

    def _target_description(self, spec: EvolveSpec, digest: str) -> str:
        lines = []
        if spec.run.repo_summary:
            lines.append(spec.run.repo_summary)
        if spec.module.description:
            lines.append(f"Module {spec.module.qualified_name}: {spec.module.description}")
        lines.append("")
        lines.append("In-scope targets:")
        for t in spec.targets:
            if t.scope_kind == "candidate" and t.line_start is not None:
                lines.append(f"- {t.file}:{t.line_start}–{t.line_end} (`{t.symbol}`)")
            else:
                role = f" — {t.role}" if t.role else ""
                lines.append(f"- {t.file} (whole file{role})")
        lines.append("")
        lines.append(digest)
        return "\n".join(lines)

    def _observable_metrics(self, spec: EvolveSpec, cand: Target) -> list[str]:
        metrics: list[str] = []
        if cand.oracles.performance:
            for part in re.split(r"[,/]", cand.oracles.performance):
                part = part.strip()
                if part and part not in metrics:
                    metrics.append(part)
        return metrics

    def _controllable_knobs(self, spec: EvolveSpec) -> list[str]:
        knobs: list[str] = []
        for t in spec.targets:
            label = f"{t.symbol} ({t.file})" if t.symbol else t.file
            if label not in knobs:
                knobs.append(label)
        return knobs

    def _theory_references(self, spec: EvolveSpec) -> list[dict]:
        refs: list[dict] = []
        for f in spec.findings:
            # Allowed keys EXACTLY: name, statement, how, use_as,
            # independent_of_detector. No url / evidence.
            refs.append(
                {
                    "name": f.title,
                    "statement": f.technique_summary,
                    "use_as": "sanity_check",
                    "independent_of_detector": False,
                }
            )
        return refs

    def _ground_truth(self, spec: EvolveSpec, cand: Target) -> dict | None:
        gt: dict = {"pre_registered": False}
        if cand.oracles.performance:
            gt["primary_metric"] = cand.oracles.performance
            gt["direction_claim"] = (
                f"{cand.oracles.performance} should "
                f"{'decrease' if spec.objective.direction == 'minimize' else 'increase'}"
            )
        if spec.objective.workload_hints:
            gt["workload"] = "; ".join(spec.objective.workload_hints)
        # pass_condition is required-ish for usefulness but has no source — leave
        # a clear TODO so the user completes it.
        gt["pass_condition"] = "TODO: define a concrete pass/fail rule"
        return gt

    # --- bundle.yaml ---

    def _build_bundle(self, spec: EvolveSpec, cand: Target) -> str:
        research_question = self._research_question(spec, cand)
        code_changes = []
        for p in spec.proposals[:3]:
            code_changes.append(
                {
                    "file": cand.file,
                    "intent": p.title,
                    "rationale": p.rationale,
                }
            )
        if not code_changes:
            code_changes.append(
                {
                    "file": cand.file,
                    "intent": f"Evolve `{cand.symbol}` per the objective",
                    "rationale": cand.evolve_rationale or "selected candidate",
                }
            )

        arm = {
            "type": "h-main",
            "prediction": (
                f"Changing `{cand.symbol}` improves "
                f"{cand.oracles.performance or 'the primary metric'} "
                f"(direction: {spec.objective.direction})."
            ),
            "mechanism": cand.current_approach
            or f"{cand.symbol} governs the hot path for the objective.",
            "diagnostic": (
                "If the prediction is wrong, inspect whether the change "
                "actually engaged the mechanism and whether the workload "
                "exercises it."
            ),
            "code_changes": code_changes,
        }
        bundle = {
            "metadata": {
                "iteration": 1,
                "family": _slug(spec.module.qualified_name),
                "research_question": research_question,
            },
            "arms": [arm],
        }
        header = "# Generated by spotlights-engine prep-evolve.\n"
        return header + dump_yaml(bundle)

    # --- vendored methodology ---

    def _vendor_methodology(self) -> list[GeneratedFile]:
        src = _find_methodology_dir()
        if src is None:
            return [
                GeneratedFile(
                    path="prompts/methodology/README.md",
                    text=(
                        "# Methodology prompts missing\n\n"
                        "prep-evolve could not locate the Nous methodology "
                        "prompts to vendor. Point `prompts.methodology_layer` "
                        "at a checkout of "
                        "agentic-strategy-evolution/prompts/methodology.\n"
                    ),
                    overwrite="always",
                )
            ]
        files: list[GeneratedFile] = []
        for path in sorted(src.glob("*.md")):
            files.append(
                GeneratedFile(
                    path=f"prompts/methodology/{path.name}",
                    text=path.read_text(encoding="utf-8"),
                    overwrite="always",
                )
            )
        return files


__all__ = ["NousAdapter"]
