"""Nous (agentic-strategy-evolution) adapter: a single self-contained
campaign.yaml.

Nous runs experiment arms whose `code_changes[]` intents the executor turns
into patches. `campaign.yaml` must respect `additionalProperties: false`, so we
emit only schema-allowed keys; URLs/evidence stay in the digest /
`target_system.description`.

The bundle is deliberately just `campaign.yaml` — no `bundle.yaml`, no vendored
methodology prompts, and no shared README. Everything the run needs is inlined
into the campaign.
"""

from __future__ import annotations

import re

from spotlights_engine.prep_evolve.adapters.base import GeneratedFile
from spotlights_engine.prep_evolve.digest import render_digest
from spotlights_engine.prep_evolve.spec import EvolveSpec, Target
from spotlights_engine.prep_evolve.yaml_emit import dump_yaml


def _candidate_target(spec: EvolveSpec) -> Target:
    for t in spec.targets:
        if t.scope_kind == "candidate":
            return t
    return spec.targets[0]


def _slug(text: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()
    return s or "run"


class NousAdapter:
    name = "nous"

    # Nous bundles are a single self-contained campaign.yaml; api.py keys off
    # this to skip the shared README.
    minimal_bundle = True

    def __init__(self, model: str | None = None) -> None:
        self._model = model

    def supports(self, spec: EvolveSpec) -> tuple[bool, str]:
        return (True, "")

    def render(self, spec: EvolveSpec) -> list[GeneratedFile]:
        digest = render_digest(spec)
        cand = _candidate_target(spec)

        return [
            GeneratedFile(
                path="campaign.yaml",
                text=self._build_campaign(spec, cand, digest),
            )
        ]

    # --- campaign.yaml ---

    def _build_campaign(self, spec: EvolveSpec, cand: Target, digest: str) -> str:
        research_question = self._research_question(spec, cand)
        run_id = _slug(
            f"{spec.run.repo_name}-{spec.module.qualified_name}-{cand.candidate_id or 'cand'}"
        )

        target_system: dict = {
            "name": spec.run.repo_name,
            "description": self._target_description(spec, digest),
        }
        metrics = self._observable_metrics(spec, cand)
        if metrics:  # minItems: 1 — omit the key entirely when empty
            target_system["observable_metrics"] = metrics
        knobs = self._controllable_knobs(spec)
        if knobs:
            target_system["controllable_knobs"] = knobs
        target_system["repo_path"] = spec.run.repo_path

        campaign: dict = {
            "research_question": research_question,
            "run_id": run_id,
            "target_system": target_system,
        }

        theory = self._theory_references(spec)
        if theory:
            campaign["theory_references"] = theory

        ground_truth = self._ground_truth(spec, cand)
        if ground_truth:
            campaign["ground_truth"] = ground_truth

        campaign["prompts"] = {"methodology_layer": "prompts/methodology"}

        if self._model:
            campaign["models"] = {"design": self._model, "execute_analyze": self._model}

        header = (
            "# Generated by spotlights-engine prep-evolve.\n"
            "# Run: NOUS_CAMPAIGN_PARENT=$PWD/nous_runs nous run campaign.yaml\n"
        )
        return header + dump_yaml(campaign)

    def _research_question(self, spec: EvolveSpec, cand: Target) -> str:
        sym = cand.symbol or cand.file
        return f"Does changing `{sym}` in {spec.run.repo_name} achieve: {spec.objective.goal}?"

    def _target_description(self, spec: EvolveSpec, digest: str) -> str:
        lines = []
        if spec.run.repo_summary:
            lines.append(spec.run.repo_summary)
        if spec.module.description:
            lines.append(f"Module {spec.module.qualified_name}: {spec.module.description}")
        lines.append("")
        lines.append("In-scope targets:")
        for t in spec.targets:
            if t.scope_kind == "candidate" and t.line_start is not None:
                lines.append(f"- {t.file}:{t.line_start}–{t.line_end} (`{t.symbol}`)")
            else:
                role = f" — {t.role}" if t.role else ""
                lines.append(f"- {t.file} (whole file{role})")
        lines.append("")
        lines.append(digest)
        return "\n".join(lines)

    def _observable_metrics(self, spec: EvolveSpec, cand: Target) -> list[str]:
        metrics: list[str] = []
        if cand.oracles.performance:
            for part in cand.oracles.performance.split(","):
                part = part.strip()
                if part and part not in metrics:
                    metrics.append(part)
        return metrics

    def _controllable_knobs(self, spec: EvolveSpec) -> list[str]:
        knobs: list[str] = []
        for t in spec.targets:
            label = f"{t.symbol} ({t.file})" if t.symbol else t.file
            if label not in knobs:
                knobs.append(label)
        return knobs

    def _theory_references(self, spec: EvolveSpec) -> list[dict]:
        refs: list[dict] = []
        for f in spec.findings:
            # Allowed keys EXACTLY: name, statement, how, use_as,
            # independent_of_detector. No url / evidence.
            refs.append(
                {
                    "name": f.title,
                    "statement": f.technique_summary,
                    "use_as": "sanity_check",
                    "independent_of_detector": False,
                }
            )
        return refs

    def _ground_truth(self, spec: EvolveSpec, cand: Target) -> dict | None:
        gt: dict = {"pre_registered": False}
        if cand.oracles.performance:
            gt["primary_metric"] = cand.oracles.performance
            gt["direction_claim"] = (
                f"{cand.oracles.performance} should "
                f"{'decrease' if spec.objective.direction == 'minimize' else 'increase'}"
            )
        if spec.objective.workload_hints:
            gt["workload"] = "; ".join(spec.objective.workload_hints)
        # pass_condition is required-ish for usefulness but has no source — leave
        # a clear TODO so the user completes it.
        gt["pass_condition"] = "TODO: define a concrete pass/fail rule"
        return gt


__all__ = ["NousAdapter"]
